### ISSUE TITLE
duplicated icons

### ISSUE THREAD

**Issue by maxlath** [datafoodconsortium/datafoodconsortium.github.io#1]
`fa-shopping-cart` is used 2 times
![dup](https://cloud.githubusercontent.com/assets/1596934/23768804/7d3beac0-050d-11e7-93af-722fb7231831.png)

Maybe you could use [fa-handshake-o](http://fontawesome.io/icon/handshake-o/) for the *Social* section? Requires to update to FA v4.7 though

**Comment by myriamboure** [comment]
@arthur-koenig I just saw this message from @maxlath I was not watching the repo ;-) Can you take care of that ? Thanks !

**Comment by myriamboure** [comment]
This was fixed long time ago but I forgot to close the issue, closing it now.
![Capture du 2019-04-05 11-28-58](https://user-images.githubusercontent.com/8135376/55618115-06a99a00-5796-11e9-975a-d9a47cc72cc7.png)
